/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForumRouteImport } from './routes/forum'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ForumIndexRouteImport } from './routes/forum.index'
import { Route as BlogsIndexRouteImport } from './routes/blogs.index'
import { Route as ProductsIdRouteImport } from './routes/products.$id'
import { Route as ForumAskRouteImport } from './routes/forum.ask'
import { Route as ForumIdRouteImport } from './routes/forum.$id'
import { Route as BlogsIdRouteImport } from './routes/blogs.$id'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumRoute = ForumRouteImport.update({
  id: '/forum',
  path: '/forum',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsRoute,
} as any)
const ForumIndexRoute = ForumIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ForumRoute,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogsRoute,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProductsRoute,
} as any)
const ForumAskRoute = ForumAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => ForumRoute,
} as any)
const ForumIdRoute = ForumIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ForumRoute,
} as any)
const BlogsIdRoute = BlogsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BlogsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blogs': typeof BlogsRouteWithChildren
  '/cart': typeof CartRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/forum': typeof ForumRouteWithChildren
  '/login': typeof LoginRoute
  '/products': typeof ProductsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/blogs/$id': typeof BlogsIdRoute
  '/forum/$id': typeof ForumIdRoute
  '/forum/ask': typeof ForumAskRoute
  '/products/$id': typeof ProductsIdRoute
  '/blogs/': typeof BlogsIndexRoute
  '/forum/': typeof ForumIndexRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/blogs/$id': typeof BlogsIdRoute
  '/forum/$id': typeof ForumIdRoute
  '/forum/ask': typeof ForumAskRoute
  '/products/$id': typeof ProductsIdRoute
  '/blogs': typeof BlogsIndexRoute
  '/forum': typeof ForumIndexRoute
  '/products': typeof ProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blogs': typeof BlogsRouteWithChildren
  '/cart': typeof CartRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/forum': typeof ForumRouteWithChildren
  '/login': typeof LoginRoute
  '/products': typeof ProductsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/blogs/$id': typeof BlogsIdRoute
  '/forum/$id': typeof ForumIdRoute
  '/forum/ask': typeof ForumAskRoute
  '/products/$id': typeof ProductsIdRoute
  '/blogs/': typeof BlogsIndexRoute
  '/forum/': typeof ForumIndexRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blogs'
    | '/cart'
    | '/forgot-password'
    | '/forum'
    | '/login'
    | '/products'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/support'
    | '/blogs/$id'
    | '/forum/$id'
    | '/forum/ask'
    | '/products/$id'
    | '/blogs/'
    | '/forum/'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/support'
    | '/blogs/$id'
    | '/forum/$id'
    | '/forum/ask'
    | '/products/$id'
    | '/blogs'
    | '/forum'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/blogs'
    | '/cart'
    | '/forgot-password'
    | '/forum'
    | '/login'
    | '/products'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/support'
    | '/blogs/$id'
    | '/forum/$id'
    | '/forum/ask'
    | '/products/$id'
    | '/blogs/'
    | '/forum/'
    | '/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogsRoute: typeof BlogsRouteWithChildren
  CartRoute: typeof CartRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ForumRoute: typeof ForumRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SupportRoute: typeof SupportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum': {
      id: '/forum'
      path: '/forum'
      fullPath: '/forum'
      preLoaderRoute: typeof ForumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/forum/': {
      id: '/forum/'
      path: '/'
      fullPath: '/forum/'
      preLoaderRoute: typeof ForumIndexRouteImport
      parentRoute: typeof ForumRoute
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/'
      fullPath: '/blogs/'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof BlogsRoute
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/forum/ask': {
      id: '/forum/ask'
      path: '/ask'
      fullPath: '/forum/ask'
      preLoaderRoute: typeof ForumAskRouteImport
      parentRoute: typeof ForumRoute
    }
    '/forum/$id': {
      id: '/forum/$id'
      path: '/$id'
      fullPath: '/forum/$id'
      preLoaderRoute: typeof ForumIdRouteImport
      parentRoute: typeof ForumRoute
    }
    '/blogs/$id': {
      id: '/blogs/$id'
      path: '/$id'
      fullPath: '/blogs/$id'
      preLoaderRoute: typeof BlogsIdRouteImport
      parentRoute: typeof BlogsRoute
    }
  }
}

interface BlogsRouteChildren {
  BlogsIdRoute: typeof BlogsIdRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
}

const BlogsRouteChildren: BlogsRouteChildren = {
  BlogsIdRoute: BlogsIdRoute,
  BlogsIndexRoute: BlogsIndexRoute,
}

const BlogsRouteWithChildren = BlogsRoute._addFileChildren(BlogsRouteChildren)

interface ForumRouteChildren {
  ForumIdRoute: typeof ForumIdRoute
  ForumAskRoute: typeof ForumAskRoute
  ForumIndexRoute: typeof ForumIndexRoute
}

const ForumRouteChildren: ForumRouteChildren = {
  ForumIdRoute: ForumIdRoute,
  ForumAskRoute: ForumAskRoute,
  ForumIndexRoute: ForumIndexRoute,
}

const ForumRouteWithChildren = ForumRoute._addFileChildren(ForumRouteChildren)

interface ProductsRouteChildren {
  ProductsIdRoute: typeof ProductsIdRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsIdRoute: ProductsIdRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogsRoute: BlogsRouteWithChildren,
  CartRoute: CartRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ForumRoute: ForumRouteWithChildren,
  LoginRoute: LoginRoute,
  ProductsRoute: ProductsRouteWithChildren,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SupportRoute: SupportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
